import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Configuração da fonte Inter, focada no subconjunto Latin
const inter = Inter({ subsets: ["latin"] });

// Definição de metadados da aplicação
export const metadata: Metadata = {
  title: "FEM STOCK",
  description: "Generated by create next app",
};

// Componente RootLayout que envolve toda a aplicação
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
