'use client'
import { BiPlus, BiUserPlus } from "react-icons/bi";
import Table from '../components/table';
import Head from 'next/head';
import Form from '../components/form';
import { useState } from "react";


export default function Home() {

const [visible, setVisible] = useState(false)
const handler = () =>{
  setVisible(visible ? false: true)
  // ou podes   setVisible(!visible) isto na hora de clicar no botão e voltar a clicar para não vermos no front.

}

  return (
    <>
      <Head>
        <title>FEM STOCK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>
          MATERIAL EXISTENTE NOS PAIÓS FEM - DONDO
        </h1>

        <div className="container mx-auto flex justify-between py-10 border-b">
          <div className="flex gap-4">
            <button onClick={handler} className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-500 hover:border-indigo-500 hover:text-gray-800'>
              <BiPlus size={23} />
              <span className='px-1'></span>
              Adicionar artigo
            </button>
            <span>Última Actualização em 20/08/2024: 17:46min</span>
          </div>
        </div>

        {/* formulario */}

        {visible ? <Form></Form>: <></>}
        {/* Seção para tabela */}
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </>
  );
}